gs_ps_ps_adv_end_houses = [{"city-plans": [{"criteria": "end houses", "position": 1, "score1": 7, "score2": 4},
                                           {"criteria": [1, 1, 1, 6], "position": 2, "score1": 11, "score2": 6},
                                           {"criteria": [1, 2, 6], "position": 3, "score1": 12, "score2": 7}],
                            "city-plans-won": [True, False, False],
                            "construction-cards": [[15, "bis"], [15, "bis"], [15, "bis"]],
                            "effects": ["bis", "pool", "pool"]},
                           {"agents": [0, 0, 0, 0, 0, 0], "city-plan-score": ["blank", "blank", "blank"], "refusals": 0,
                            "streets": [{"homes": [0, False, [False, [0, "bis"], False], [False, 3, False],
                                                   [False, 4, False], [False, "blank", False], [False, 7, False],
                                                   [False, 9, False], [False, 11, False], [False, [14, "bis"], False],
                                                   [False, 14, False]], "parks": 0, "pools": [False, False, False]}, {
                                            "homes": [1, False, [False, 2, False], [False, 3, False], [False, 4, False],
                                                      [False, 5, False], [False, 6, False], [False, 7, False],
                                                      [False, 8, False], [False, 9, False], [False, 10, False],
                                                      [False, 11, False]], "parks": 1, "pools": [False, False, False]},
                                        {"homes": [1, False, [False, 2, False], [False, 3, False], [False, 4, False],
                                                   [False, "blank", False], [False, "blank", False], [False, 8, False],
                                                   [False, 9, False], [False, 10, False], [False, 11, False],
                                                   [False, 12, False], [False, "blank", False]], "parks": 2,
                                         "pools": [False, False, False]}], "temps": 0},
                           {"agents": [0, 0, 0, 0, 0, 0], "city-plan-score": [4, "blank", "blank"], "refusals": 0,
                            "streets": [{"homes": [0, True, [False, [0, "bis"], False], [False, 3, False],
                                                   [False, 4, False], [False, "blank", False], [False, 7, False],
                                                   [False, 9, False], [False, 11, False], [False, [14, "bis"], False],
                                                   [False, 14, True]], "parks": 0, "pools": [False, False, False]}, {
                                            "homes": [1, True, [False, 2, False], [False, 3, False], [False, 4, False],
                                                      [False, 5, False], [False, 6, False], [False, 7, False],
                                                      [False, 8, False], [False, 9, False], [False, 10, False],
                                                      [False, 11, True]], "parks": 1, "pools": [False, False, False]}, {
                                            "homes": [1, True, [False, 2, False], [False, 3, False], [False, 4, False],
                                                      [False, "blank", False], [False, "blank", False],
                                                      [False, 8, False], [False, 9, False], [False, 10, False],
                                                      [False, 11, False], [False, 12, False], [False, 15, True]],
                                            "parks": 2, "pools": [False, False, False]}], "temps": 0}]


gs_ps_ps_invalid = [{"city-plans": [{"criteria": [1, 1, 1, 1, 1, 1], "position": 1, "score1": 8, "score2": 4},
                                    {"criteria": [1, 1, 1, 6], "position": 2, "score1": 11, "score2": 6},
                                    {"criteria": [1, 2, 6], "position": 3, "score1": 12, "score2": 7}],
                     "city-plans-won": [False, False, False],
                     "construction-cards": [[1, "surveyor"], [5, "landscaper"], [7, "pool"]],
                     "effects": ["landscaper", "bis", "surveyor"]},

                    {"agents": [0, 0, 0, 1, 0, 0],
                     "city-plan-score": ["blank", "blank", "blank"],
                     "refusals": 0,
                     "streets": [
                         {"homes": [1, False, [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False]],
                          "parks": 0,
                          "pools": [False, False, False]},
                         {"homes": ["blank", False, [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False], [False, "blank", False]],
                          "parks": 0,
                          "pools": [False, False, False]},
                         {"homes": ["blank", False, [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False]],
                          "parks": 0,
                          "pools": [False, False, False]}],
                     "temps": 0},

                    {"agents": [0, 0, 0, 1, 0, 0],
                     "city-plan-score": ["blank", "blank", "blank"],
                     "refusals": 0,
                     "streets": [
                         {"homes": [1, False, [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False]],
                          "parks": 0,
                          "pools": [False, False, False]},
                         {"homes": ["blank", False, [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False], [False, "blank", False]],
                          "parks": 0,
                          "pools": [False, False, False]},
                         {"homes": ["blank", False, [False, "blank", False], [False, 7, False], [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False],
                                    [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                    [False, "blank", False]],
                          "parks": 1,
                          "pools": [False, False, False]}],
                     "temps": 0}]

gs_ps_ps_house_num = [{"city-plans": [{"criteria": [1, 1, 1, 1, 1, 1], "position": 1, "score1": 8, "score2": 4},
                                      {"criteria": [1, 1, 1, 6], "position": 2, "score1": 11, "score2": 6},
                                      {"criteria": [1, 2, 6], "position": 3, "score1": 12, "score2": 7}],
                       "city-plans-won": [False, False, False],
                       "construction-cards": [[7, "bis"], [7, "bis"], [7, "bis"]],
                       "effects": ["surveyor", "pool", "temp"]},

                      {"agents": [0, 0, 0, 0, 0, 0], "city-plan-score": ["blank", "blank", "blank"], "refusals": 0,
                       "streets": [{"homes": [
                           "blank", False, [False, "blank", False], [False, "blank", False], [False, "blank", False],
                           [False, "blank", False],
                           [False, "blank", False], [False, "blank", False], [False, "blank", False],
                           [False, "blank", False],
                           [False, "blank", False]], "parks": 0, "pools": [False, False, False]},
                           {"homes": ["blank", False,
                                      [False, "blank", False],
                                      [False, "blank", False],
                                      [False, "blank", False],
                                      [False, "blank", False],
                                      [False, "blank", False],
                                      [False, "blank", False],
                                      [False, "blank", False],
                                      [False, "blank", False],
                                      [False, "blank", False],
                                      [False, "blank", False]],
                            "parks": 0,
                            "pools": [False, False, False]}, {
                               "homes": [
                                   "blank",
                                   False,
                                   [
                                       False,
                                       "blank",
                                       False],
                                   [
                                       False,
                                       "blank",
                                       False],
                                   [
                                       False,
                                       "blank",
                                       False],
                                   [
                                       False,
                                       "blank",
                                       False],
                                   [
                                       False,
                                       "blank",
                                       False],
                                   [
                                       False,
                                       "blank",
                                       False],
                                   [
                                       False,
                                       "blank",
                                       False],
                                   [
                                       False,
                                       "blank",
                                       False],
                                   [
                                       False,
                                       "blank",
                                       False],
                                   [
                                       False,
                                       "blank",
                                       False],
                                   [
                                       False,
                                       "blank",
                                       False]],
                               "parks": 0,
                               "pools": [
                                   False,
                                   False,
                                   False]}],
                       "temps": 0},

                      {"agents": [0, 0, 0, 0, 0, 0], "city-plan-score": ["blank", "blank", "blank"], "refusals": 0,
                       "streets": [{"homes": ["blank", False, [False, "blank", False], [False, "blank", False],
                                              [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                              [False, "blank", False], [False, "blank", False], [False, "blank", False],
                                              [False, "blank", False]], "parks": 0, "pools": [False, False, False]}, {
                                       "homes": ["blank", False, [False, "blank", False], [False, "blank", False],
                                                 [False, "blank", False], [False, 7, False], [False, "blank", False],
                                                 [False, "blank", False], [False, "blank", False],
                                                 [False, "blank", False],
                                                 [False, "blank", False], [False, "blank", False]], "parks": 0,
                                       "pools": [False, False, False]}, {
                                       "homes": ["blank", False, [False, "blank", False], [False, "blank", False],
                                                 [False, "blank", False], [False, "blank", False],
                                                 [False, "blank", False],
                                                 [False, "blank", False], [False, "blank", False],
                                                 [False, "blank", False],
                                                 [False, "blank", False], [False, "blank", False], [False, 7, False]],
                                       "parks": 0, "pools": [False, False, False]}], "temps": 0}]

