download-java run:
	wget "https://download.java.net/java/GA/jdk13/5b8a42f3905b406298b72d750b6919f6/33/GPL/openjdk-13_linux-x64_bin.tar.gz"
	
	tar -xf openjdk-13_linux-x64_bin.tar.gz
	
	echo "java binaries are now in ./jdk-13/bin/"
	chmod u+x run